### ISSUE TITLE
how to limit the number of timer loop?

### ISSUE THREAD

**Issue by irandoct** [caike/jQuery-Simple-Timer#38]
Hi,
I want to specify the number of the timer loop! I can set the loop interval but I don't know how to limit the loop number?!
any idea?
thanks
Mansour

**Comment by caike** [comment]
By _loop number_ do you mean _the number of times the timer is allowed to loop before completing_ ? If that's the case, then I don't believe this feature exists. That's a great feature idea, though! Since this is not a priority for me atm, I'll mark it as an enhancement for now in case anyone wants to submit a PR before I get to it.
